services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - agenda-data:/app/data
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DATABASE_PATH=/app/data/db.sqlite3

volumes:
  agenda-data:
