# Generated by Django 5.2.15 on 2026-06-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], default='whatsapp', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(choices=[('confirmed', 'Confirmado'), ('not_confirmed', 'Não confirmado'), ('no_response', 'Sem resposta')], default='no_response', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('responded', 'Respondida'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('delivery_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('scheduled_for',),
            },
        ),
    ]
