# Generated by Django 5.2.15 on 2026-06-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_presenceconfirmation'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenceconfirmation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence_confirmation', to='scheduling.appointment'),
        ),
        migrations.AddIndex(
            model_name='presenceconfirmation',
            index=models.Index(fields=['status', 'scheduled_for'], name='messaging_p_status_b2b11e_idx'),
        ),
    ]
