# Generated by Django 5.2.15 on 2026-06-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_presenceconfirmation_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('state', models.CharField(choices=[('idle', 'Ocioso'), ('awaiting_specialty', 'Aguardando especialidade'), ('awaiting_slot', 'Aguardando horário'), ('awaiting_confirm', 'Aguardando confirmação')], default='idle', max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
